server:
  port: 8081
spring:
  application:
    name: order-microservice
  datasource:
    url: postgresql://localhost:5000/order-microservice
    username: gus
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true